### ISSUE TITLE
Nice utility

### ISSUE THREAD

**Issue by enkianu** [Kixiron/JunkyPy#1]
Thanks for this tool. Would appreciate if you gave a working tutorial on how to make it work. I've tried running this using several versions of python and can't seem to get it to work.

**Comment by Kixiron** [comment]
Sure! Most of the tool is configured via interactive prompt once you start the program. If I'm being honest, it's been so long since I created this that it forgot it existed, but I'd be happy to help in any way that I can!

**Comment by enkianu** [comment]
I've been able to learn how it works. Thanks
